version: '3.8'

services:
  app:
    image: madbadrat/guitarshop:latest
    container_name: guitarshop-container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/guitarshop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=guitarshop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local